name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v5

      - name: Setup Bun
        id: setup-bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: '.bun-version'

      - name: Install Dependencies
        id: bun-ci
        run: bun install --frozen-lockfile

      - name: Check Format
        id: bun-format-check
        run: bun run format:check

      - name: Lint
        id: bun-lint
        run: bun run lint

      - name: Test
        id: bun-ci-test
        run: bun run test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v5

      - name: Test Local Action
        if: false
        id: test-action
        uses: ./
        with:
          oci-user: ${{ secrets.OCI_USER }}
          oci-tenancy: ${{ secrets.OCI_TENANCY }}
          oci-fingerprint: ${{ secrets.OCI_FINGERPRINT }}
          oci-key-content: ${{ secrets.OCI_KEY_CONTENT }}
          oci-region: ${{ secrets.OCI_REGION }}
          bastion-id: ${{ secrets.BASTION_ID }}
          public-key: ${{ secrets.SESSION_PUBLIC_KEY }}
          session-ttl-seconds: 1800
          session-type: ${{ vars.SESSION_TYPE}}
          target-resource-id: ${{ secrets.TARGET_RESOURCE_ID }}
          target-resource-user: ${{ secrets.TARGET_RESOURCE_USER }}
          auto-enable-bastion-plugin: true

      - name: Print Output
        id: output
        run: |
          echo "session-id: ${{ steps.test-action.outputs.session-id }}"
          cat <<EOF
          ssh-command: ${{ steps.test-action.outputs.ssh-command }}
          EOF
