name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        id: setup-bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: '.bun-version'

      - name: Install Dependencies
        id: bun-ci
        run: bun install --frozen-lockfile

      - name: Check Format
        id: bun-format-check
        run: bun run format:check

      - name: Lint
        id: bun-lint
        run: bun run lint

      - name: Test
        id: bun-ci-test
        run: bun run test
