name: Dependabot Build

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: read

jobs:
  build:
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    name: Build dist/
    runs-on: ubuntu-latest

    steps:
      - name: Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v2

      - name: Checkout
        if: ${{ steps.dependabot-metadata.outputs.package-ecosystem == 'bun' }}
        id: checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Bun
        if: ${{ steps.dependabot-metadata.outputs.package-ecosystem == 'bun' }}
        id: setup-bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: '.bun-version'

      - name: Install Dependencies
        if: ${{ steps.dependabot-metadata.outputs.package-ecosystem == 'bun' }}
        id: install
        run: bun install

      - name: Build dist/ Directory
        if: ${{ steps.dependabot-metadata.outputs.package-ecosystem == 'bun' }}
        id: build
        run: bun run bundle

      - name: Update Pull Request
        if: ${{ steps.dependabot-metadata.outputs.package-ecosystem == 'bun' }}
        id: update-pr
        run: |
          git config core.autocrlf false
          git config core.eol lf

          if [[ `git status --porcelain` ]]; then
            git config --global user.name "dependabot[bot]"
            git config --global user.email "dependabot[bot] <support@github.com>"
            git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
            git add -A

            if git commit -m "Update dist/ directory"; then
              git push -u origin HEAD:${{ github.event.pull_request.head.ref }}
            else
              echo "No changes to commit"
            fi
          else
            echo "No changes to commit"
          fi
